-- SQL INSERT statements for books data from books.csv
-- Includes all book attributes with image URLs
-- All books initialized with statut = DISPONIBLE

-- Create the auteurs table if it doesn't exist
CREATE TABLE IF NOT EXISTS auteurs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    biographie TEXT
);

-- Create the livres table if it doesn't exist
CREATE TABLE IF NOT EXISTS livres (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    genre VARCHAR(255),
    description TEXT,
    annee INT,
    isbn VARCHAR(20),
    image_url VARCHAR(500),
    statut VARCHAR(20) DEFAULT 'DISPONIBLE',
    auteur_id BIGINT,
    FOREIGN KEY (auteur_id) REFERENCES auteurs(id)
);

-- Ensure image_url column exists in the livres table

-- Insert all books from CSV with all attributes and image URLs
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Oral and Maxillofacial Surgery: An Objective-Based Textbook, 2e', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41kSLEoswsL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Barron\'s GRE, 21st Edition', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/510l0qhi01L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('George Balanchine: The Ballet Maker (Eminent Lives)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51p5aUY%2BOKL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A Partner in Holiness: Deepening Mindfulness, Practicing Compassion and Enriching Our Lives Through the Wisdom of R. Levi Yitzhak of Berdichev\'s, Vol. 2  (Institute for Jewish Spirituality)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51pum0eWe4L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Construction Scheduling: Principles and Practices (2nd Edition)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51PuTPPCxaL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Literature and Its Writers: A Compact Introduction to Fiction, Poetry, and Drama', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51uNnIlIwrL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Straight on Till Morning: The Life of Beryl Markham', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51VIlqRy-VL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Diagrammatica: The Path to Feynman Diagrams (Cambridge Lecture Notes in Physics)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41n7iZq-0jL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Book of Common Prayer 1979: Large Print edition', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41xLYt-v6nL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A Handful of Stars', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51KyLXczCqL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Almost Anorexic: Is My (or My Loved One\'s) Relationship with Food a Problem? (The Almost Effect)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51Jku59B9CL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Pre-ANDA Litigation: Strategies and Tactics for Developing a Drug Product and Patent Portfolio', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41LkijoCvuL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Creative, Successful, Dyslexic: 23 High Achievers Share Their Stories', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51Tjv23guEL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Organ Transplantation (Health and Medical Issues Today)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51C16779N8L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Age of Acquiescence: The Life and Death of American Resistance to Organized Wealth and Power', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51JFeqcU96L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Multiples Manual: Preparing and Caring for Twins or Triplets', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51kOYa-LHML.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Oregon High: A Climbing Guide to Nine Cascade Volcanoes', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51bWdcsbX0L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('HTML & XHTML: The Definitive Guide (6th Edition)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/5159f7hqJjL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Anti Inflammatory Cookbook - 50 Slow Cooker Recipes With Anti - Inflammatory Ingredients: Great For Gout! (Slow Cooker Cookbooks)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/5178fq2DV3L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Leopard Geckos (Complete Herp Care)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51zi2q5JfbL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Botswana & Its National Heritage', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51AdbQZwDuL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Eat the Rich: A Treatise on Economics', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51EdPM0rHkL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Paw Patrol Phonics Box Set (PAW Patrol) (Step into Reading)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51V7y865BxL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Official Doctor Who2016 Square Calendar', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61Yudxp-yeL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Battlefields of the Civil War Map', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51t0aUEe0tL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('5 Centimeters per Second', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51IybjClfrL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Story of the New Orleans Hornets (The NBA: a History of Hoops)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51AiMilDWpL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Love in Provence: Romantic Adventures in the South of France', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51t2uBEMp3L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Polymeric Multicomponent Materials: An Introduction', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41aVeVvefKL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Fantasy League', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51TI3FwVa%2BL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Be the Ultimate Assistant: A celebrity assistant\'s secrets to working with any high-powered employer', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/31VJtBTmfvL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Parables: The Greatest Stories Ever Told (Lifeguide Bible Studies)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51pnw9xXOtL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Bali Travels Maldives [Japanese Edition]', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51pqgSj8YoL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Microsoft Windows Security Essentials', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/518VXqYR27L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Shadowrun: Third Edition (FPR25000)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51TLjyIjU%2BL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Crime Wave: Collected Nonfiction (The Ace Performer Collection series)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51uJz4Jd-hL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The English Country House Garden', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61c4EZtdtNL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Diary of Anne Frank', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51JXp76wG1L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('ICD-10-CM 2015: The Complete Official Codebook', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41uPslzVRgL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Words of Gandhi (Newmarket Words Of Series)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/410oYwwjssL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Shortcut', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61gCGr0YMzL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Medical Mycology: Cellular and Molecular Techniques', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41LiDBXEC-L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The First Third', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51ssxbQig9L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Reasons Mommy Drinks', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41hJGXQAq%2BL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Manual of High Risk Pregnancy and Delivery, 5e (Manual of High Risk Pregnancy & Delivery)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41eD1Ln0KlL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Oscillations and Waves: An Introduction', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41XfKAnD%2BgL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('DAMAGES', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51hCxlTZ5EL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Sermons on Timothy and Titus (16th-17th Century Facsimile Edition)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41oo7KfL5ML.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Oils and Vinegars: Discovering and Enjoying Gourmet Oils and Vinegars', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51U6eq7vu4L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Handbook of Painted Decoration: The Tools, Materials, and Step-by-Step Techniques of Trompe L\'Oeil Painting', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51BLmSCM6dL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Stage Plays from the Classics: One-Act Adaptations from Famous Short Stories, Novels, and Plays', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41ANPWYHPBL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Runner\'s World Meals on the Run: 150 energy-packed recipes in 30 minutes or less', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61INLFujcpL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Mosaics Inside & Out: Patterns and Inspirations for 17 Mosaic Projects', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61zJetR%2BnFL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('She Appears! Encounters with Kwan Yin, Goddess of Compassion', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61Yo1Mi1JOL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A Companion to Museum Studies', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51N4hEjfIyL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('United States History  Early Years (Level 5): Houghton Mifflin Social Studies', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51EU06TQR0L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Indoor Marijuana Horticulture: The Indoor Bible', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51EU06TQR0L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('This Book Is Full of Spiders: Seriously, Dude, Don\'t Touch It (John Dies at the End)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51-RntCdC-L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Secret to Long Life in Your DNA: The Beljanski Approach to Cellular Health', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51HI3R5ucDL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Rabbi Israel Salanter and the Mussar Movement: Seeking the Torah of Truth', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41LS0LgettL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Healthiest City: Milwaukee and the Politics of Health Reform', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51WTCse4XRL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('My Fair Gentleman (Proper Romance) (A Proper Romance)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51T3GSdb4hL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Stand Up Paddling: Flatwater to Surf and Rivers (Mountaineering Outdoor Experts) (Moes)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51fgYDde-zL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Your Guide to Zion and Bryce Canyon (True North Series)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51SCBOPtu0L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Unnatural Talent: Creating, Printing and Selling Your Comic in the Digital Age', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51rpRrPuNwL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Brainstorm: The Power and Purpose of the Teenage Brain', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41TQKcxPcIL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('E-Commerce Concepts', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51b4r8w9r7L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Well Enough Alone: A Cultural History of My Hypochondria', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61lX5yjQf%2BL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Basic and Clinical Pharmacology 13 E', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61x8Dfxs9CL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('How to Have a Big Wedding on a Small Budget', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51F1112Q6ML.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Russian Grammar (Quickstudy: Academic)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51bazlq7u6L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Responsible Travel Guide Cambodia', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51DMugmdAuL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Principles of Marketing (16th Edition) (Newest Edition)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51MyuNfkVGL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Halo: The Poster Collection', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51O2-prLrML.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Mercy Watson: Something Wonky this Way Comes', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51gO81UQHXL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('If You\'re Lucky', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51moAp8QXyL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Great-Tasting Potatoes Cookbook', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51jnErh-u9L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Kuwaiti Oil Fires (Environmental Disasters)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/512NdDiYqZL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Healing Without Medication: A Comprehensive Guide to the Complementary Techniques Anyone Can Use to Achieve Real Healing', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51F3KTDSSRL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Eternity\'s Sunrise: The Imaginative World of William Blake', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51QRtiFZJtL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Paraguay (Bradt Travel Guide)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51VnUTL5nKL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Treating Trauma and Traumatic Grief in Children and Adolescents', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41I2zm6GAyL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A Terrible Revenge: The Ethnic Cleansing of the East European Germans', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/419TDqP99jL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Plastics: America\'s Packaging Dilemma (Island Press Critical Issues Series)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51Y2pTdUbLL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Microbiologically Safe Foods', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/519W7i65J%2BL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Life Reimagined: Discovering Your New Life Possibilities', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41d0t0efHaL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('It\'s St. Patrick\'s Day (Turtleback School & Library Binding Edition) (Scholastic Reader: Level 1 (Pb))', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51lXAnDj5RL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Strands of Sorrow (Black Tide Rising)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61HmWM642cL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Analytic Philosophy', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51U5u9K%2BABL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Modern Coral Reef Aquarium, Volume 2 (v. 2)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/714CGZPM6WL.gif', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Promises Kept: The Life of an Issei Man', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51HdaoFLOpL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Vocabulary for the College Bound Student', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/513K01ND32L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Hunting the Rockies: Home of the Giants', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41MXQ3Z8AVL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Slums of Aspen: Immigrants vs. the Environment in America\'s Eden (Nation of Nations)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61tWZaKGBUL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Disaster Law and Policy, Second Edition (Aspen Elective)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41-nm-fpWmL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Mobile & Social Game Design: Monetization Methods and Mechanics, Second Edition', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51wRE04dZ9L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Ready, Freddy! #22: Science Fair Flop', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51A2z8I-4DL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('HSPT Flashcard Study System: HSPT Exam Practice Questions & Review for the High School Placement Test (Cards)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51i%2Beq1ghKL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('On the Backroad to Heaven: Old Order Hutterites, Mennonites, Amish, and Brethren (Center Books in Anabaptist Studies)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41oTzSlSYuL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Spiritual Astrology: A Path to Divine Awakening', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51PtnNC45mL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Passing on Bypass Using External CounterPulsation : An FDA Cleared Alternative to Treat Heart Disease Without Surgery, Drugs or Angioplasty. SECOND EDITION', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/511TCMQWH0L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Walking the Walk (w/DVD): Getting Fit with Faith', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51KP8VqIdzL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('New Jersey Puzzle Book (Which Way USA?)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61htcGwMUYL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Best American Essays of the Century (The Best American Series)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51rSqE9IomL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('God Made All of Me: A Book to Help Children Protect Their Bodies', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/414hFvfvh9L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Classic baseball cards: The golden years, 1886-1956', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51S%2B3WLbwyL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Garfield 2016 Day-to-Day Calendar', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51g4FFUldvL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Beyond Courage: The Untold Story of Jewish Resistance During the Holocaust', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/512jvo6DxIL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Scientist as Rebel (New York Review Books)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51r8yBsTUVL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Life and Love of Dogs', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51c2TA1x6NL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Fish Tales: Stories & Recipes from Sustainable Fisheries Around the World', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51IPAyIE3yL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Health: The Basics (11th Edition)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/516Mn8i0SlL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Unprocessed: How to achieve vibrant health and your ideal weight.', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41yWRlaelL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('U.S. Army Special Forces Guide to Unconventional Warfare: Devices and Techniques for Incendiaries', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51s40bqSiWL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Most Important Year in a Woman\'s Life, The/The Most Important Year in a Man\'s Life', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41fDuKMDPyL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Texas Birds: A Folding Pocket Guide to Familiar Species (Pocket Naturalist Guide Series)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41Ks0uyRNaL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A-Z of Embroidery Stitches 2 (A-Z of Needlecraft)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61LklDw%2BcyL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Maverick of Copper Creek (Copper Creek Cowboys)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51YsvDPxuuL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Monster High: The Scary Cute Collection', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51gFmrZ0WsL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The ADA Practical Guide to Soft Tissue Oral Disease', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51jrQ7p9bHL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('They Wished They Were Honest: The Knapp Commission and New York City Police Corruption', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41ZD5vbOhFL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('What Horses Reveal: From First Meeting to Friend for Life', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51LBdueNQVL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Vital Breath of the Dao: Chinese Shamanic Tiger Qigong', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41a6jrneZ5L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('iPhone Application Development For Dummies', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51BPjyAxiFL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Ian Fleming Introduces Jamaica', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/31zoocO9QuL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Art for London Transport 2015 Calendar', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51jdZBx6bPL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Seneca: Epistles 66-92 (Loeb No. 76)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41cuXWA04fL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Wild', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/619IbdUtRLL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Principles of Optics: Electromagnetic Theory of Propagation, Interference and Diffraction of Light', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41UjGlA4QpL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('No More Fatigue: Why You\'re So Tired and What You Can Do About It', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51Mx0Zj7YDL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A Social Security Owner\'s Manual, 3rd Edition: Your Guide to Social Security Retirement, Dependent\'s, and Survivor\'s Benefits', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51gYRiiTRIL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The New Testament: A Historical Introduction to the Early Christian Writings', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51sfa8q-0mL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Stephen Irwin', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41Mqp%2BCRhJL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Rewind Files', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51P9WLKoZlL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Mao: The Unknown Story', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/519FQVMBXNL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Swimming: Swimming Made Easy- Beginner and Expert Strategies For Becoming A Better Swimmer (Swimming, Swimmers Guide, Swim Strokes, Swimming Better)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51hFggrZpWL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('British Diecast Model Toys Catalogue by John Ramsay (Editor) (1-Nov-2001) Hardcover', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51L5YeZMjlL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Sherlock Holmes: The Major Stories with Contemporary Critical Essays (Bedford Series in History & Culture)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41ST0F0KHEL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A is for Abinadi: An Alphabet Book of Scripture Heroes', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51jdaDPsQGL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Zoonosi e sanitØ£Â  pubblica: Un approccio interdisciplinare per un problema emergente (Italian Edition)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51ioF6W-0iL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Potatoes (The Australian Women\'s Weekly Essentials)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51FHMBWB47L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Bride in the Solomons', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/414F2pr0WYL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Consumerism (Opposing Viewpoints)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/31D1OY8znXL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Social Media Marketing All-in-One For Dummies', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/514zdYKrw3L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Fallacies of the Anti Hadith argument', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51Ph%2BhRkRJL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Invitation to Dynamical Systems (Dover Books on Mathematics)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51xZGUIv2mL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The 7-Day Flat-Belly Tea Cleanse: The Revolutionary New Plan to Melt Up to 10 Pounds of Fat in Just One Week!', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51twr-9ltZL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Moomin Book Five: The Complete Tove Jansson Comic Strip', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/613ZgVHpDZL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Kentucky Wildcats Fans\' Bucket List', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51xZGUIv2mL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Coaching the Complete Triple Gun Offense', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51ZlinVOoVL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Supply Chain Management: Strategy, Planning and Operations', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/515JJGFGRJL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('America : A Patriotic Primer', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/515fhWsXMTL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Black Earth: The Holocaust as History and Warning', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61yehdo5pSL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Agricola Cookbook', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61QqmtDBSVL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('A Philosophical Retrospective: Facts, Values, and Jewish Identity (Columbia Themes in Philosophy)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41QG1XFvU%2BL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Kokology: The Game of Self-Discovery', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51JcyBoDSiL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Growing Hawaii\'s Native Plants: A Simple Step-by-Step Approach for Every Species', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61gy9RISjNL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Law Enforcement In The United States', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/518jDgHO7DL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Kuan Yin Oracle Set', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51wLn0J3-bL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Biological Models in Radiopharmaceutical Development (Developments in Nuclear Medicine)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/31m5vpdap1L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Indiana: Off the beaten path (Off the Beaten Path Indiana)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51wLn0J3-bL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('For the Love of 2am: Poetry For Insomniacs', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41dESb94nVL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('In a World of Gods and Goddesses: The Mystic Art of Indra Sharma', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61Nco%2BF3jsL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Introduction to Psychology', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51ddN9xBrhL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('CLEP Micro & Macro Economics Examinations Essential Study References 2013', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51aUxUejLKL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('An Acre of Glass: A History and Forecast of the Telescope', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/418RA0MCCCL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Miracle of Castel Di Sangro', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51-qMt1dInL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Tales of King Arthur (Library of Fantasy & Adventure)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/518GSGH06HL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Visit the Zoo, vol. VI', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51LXcIqLB1L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Asset Building & Community Development', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51e8RG1XGcL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Highland Harmony: Avelina and Drew (Clan Grant Series) (Volume 8)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51ISJZX4GXL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Gems from the Equinox: Instructions by Aleister Crowley for His Own Magical Order', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41uhmxTam-L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Rick Steves\' Europe DVD: Germany, the Swiss Alps, and Travel Skills (Rick Steves\' Europe)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51PPPPG1W9L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Mast Brothers Chocolate: A Family Cookbook', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/61i-CtSmjZL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Trigger Points (Quickstudy: Academic)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51y9qRT4exL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Active Birth: The New Approach to Giving Birth Naturally (Non)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51GynpJFAQL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('What\'s The Deal With Bitcoins?', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41EwHr9af5L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Elfrida Goto Trilogy (The Solarian War Saga Books 1-3): Three Full-Length Thrilling Space Opera Novels', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51pGeuuTZeL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Leyte 1944: Return to the Philippines (Campaign)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51N9h8%2BvIlL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Never Forget About Me', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/41pnyAVQMCL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('The Illustrated Encyclopedia of Camellias', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51TNPZAFT9L.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Medicina Prehispanica De Mexico/Prehispanic Medicine of Mexico (Spanish Edition)', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51j4m1W1FeL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Warning: When I Am an Old Woman I Shall Wear Purple', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/515f1-BG5TL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Research Methods in Psychology', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51m-36WTujL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Underfoot: A Geologic Guide to the Appalachian Trail', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51FB4FBHZGL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Cascade Lodge : The History of a North Shore Landmark', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51iLDyq0BeL.jpg', 'DISPONIBLE');
INSERT INTO livres (titre, genre, description, annee, isbn, image_url, statut) VALUES ('Free from OCD: A Workbook for Teens with Obsessive-Compulsive Disorder', '', '', NULL, '', 'http://ecx.images-amazon.com/images/I/51WLN3FMKtL.jpg', 'DISPONIBLE');
